# Generated by Django 4.1 on 2022-08-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.FloatField()),
                ("sex", models.FloatField()),
                ("bmi", models.FloatField()),
                ("children", models.FloatField()),
                ("smoker", models.FloatField()),
                ("region", models.FloatField()),
                ("charges", models.FloatField()),
            ],
        ),
    ]
